[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
remappings = [
    "solady/=lib/Solady/",
    "solmate/=lib/solmate/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
    "@gnosis.pm/safe-contracts/contracts/=lib/safe-contracts/contracts",
]

[fmt]
line_length = 120
bracket_spacing = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
